// 本文件由工具从前端模板文件生成，存储平台默认模板内容。
// 如需调整默认模板，请同步修改 apps/dh-frontend/src/lib/doc-templates.ts
// 与 apps/dh-frontend/src/lib/standard-templates.ts 后重新生成。
package service

import "github.com/deepharness/deepharness-ent-platform/apps/dh-backend/domain/platformtemplate/object"

const ProductDemandTemplateContent = "# 产品需求文档（PRD）\n\n## 一、需求背景\n\n1. 业务场景：描述当前业务现状与痛点\n2. 目标用户：明确需求服务的用户群体\n3. 业务价值：说明需求上线后的预期收益\n\n## 二、需求目标\n\n- 核心目标1：可量化的业务指标\n- 核心目标2：可量化的用户价值\n\n## 三、功能详情\n\n### 3.1 功能逻辑\n\n详细描述功能规则、页面流程、判断逻辑\n\n### 3.2 交互说明\n\n描述正常流程、异常场景、边界情况处理\n\n## 四、验收标准\n\n1. 功能逻辑符合需求描述\n2. 无阻塞性、严重性 bug\n3. 交互流畅符合用户预期\n\n## 五、附录\n\n原型链接、设计稿、参考资料等\n"

const ProductMeetingTemplateContent = "# 会议纪要\n\n**会议时间：** XXXX-XX-XX XX:XX\n**参会人员：** XXX、XXX、XXX\n**会议主题：** XXX项目需求评审/方案讨论\n\n---\n\n## 一、会议议题\n\n本次会议核心讨论的事项与背景\n\n## 二、讨论结论\n\n- 结论1：明确决议内容与责任人\n- 结论2：明确决议内容与责任人\n\n## 三、待办事项\n\n| 事项内容 | 负责人 | 截止时间 |\n| --- | --- | --- |\n| 完成需求文档修改 | 张三 | XX月XX日 |\n"

const ProductWeeklyTemplateContent = "# 工作周报\n\n**汇报周期：** XXXX.XX.XX - XXXX.XX.XX\n**汇报人：** XXX\n\n---\n\n## 一、本周工作完成\n\n- 【项目A】完成XX功能开发，已提测\n- 【项目B】完成需求评审，进入开发阶段\n- 【线上问题】修复XXbug，已上线验证\n\n## 二、下周工作计划\n\n- 启动XX需求开发\n- 完成XX功能联调测试\n- 输出XX技术方案文档\n\n## 三、问题与支持\n\n描述当前遇到的阻塞问题、需要协调的资源\n"

const ProductBugTemplateContent = "# Bug反馈单\n\n**所属模块：** XXX页面/功能模块\n**严重等级：** ■ 高 □ 中 □ 低\n**发现人：** XXX\n\n---\n\n## 复现步骤\n\n1. 进入XX页面\n2. 点击XX按钮/执行XX操作\n3. 出现异常现象\n\n## 预期结果\n\n描述正确的功能表现与用户预期\n\n## 实际结果\n\n描述当前异常表现，可附截图\n\n## 环境信息\n\n浏览器：Chrome 120+\n操作系统：Windows 11 / MacOS 14\n"

const DesignUiTemplateContent = "# UI 视觉设计规范\n\n## 一、色彩规范\n\n1. **主色**：品牌主色 1 个，用于主要按钮、选中态、关键信息强调\n2. **辅助色**：不超过 2 个，用于次要信息与视觉层次\n3. **功能色**：成功（绿）、警告（黄）、错误（红）、信息（蓝）四色固定语义，禁止混用\n4. **中性色**：文本/背景/边框使用统一灰阶（建议 5~8 档），文本分一级/二级/三级/禁用四个层级\n5. 配色比例遵循 6:3:1（主色：辅助色：强调色）；正文对比度满足 WCAG AA（≥ 4.5:1）\n6. 所有颜色以 Design Token 命名管理（如 `color-primary-default`、`color-text-secondary`），禁止在页面中硬编码色值\n\n## 二、字体规范\n\n1. 字体家族统一（中文 / 英文 / 数字各一套），全产品不超过 2 套\n2. 字号层级固定：大标题 / 标题 / 小标题 / 正文 / 辅助文字 / 注释（建议 24/20/16/14/12 五档以内）\n3. 字重不超过 3 档（Regular / Medium / Semibold）；行高为字号的 1.4~1.6 倍\n4. 数字展示统一使用等宽或表格数字字体，便于对齐比较\n\n## 三、间距与圆角\n\n1. 间距基于 8px 栅格体系：4/8/12/16/24/32/48 七档，禁止出现栅格外的任意值\n2. 页面边距、卡片内边距、元素间距从间距 Token 中选取\n3. 圆角分档统一：小（4px，标签/徽标）、中（8px，按钮/输入框）、大（12~16px，卡片/弹窗）\n\n## 四、图标与图片\n\n1. 图标使用统一图标库，线性/面性风格一致；尺寸分档（16/20/24px），视觉重心对齐\n2. 同一功能全产品使用同一图标，图标表意需符合用户认知（如信封=邮件）\n3. 图片比例按场景固定（如封面 16:9、头像 1:1），提供缺省占位图\n\n## 五、阴影与层级\n\n1. 阴影分 2~3 档（卡片常驻 / 悬浮抬升 / 弹窗浮层），禁止随意自定义\n2. 层级（z-index）统一管理：页面内容 < 吸顶导航 < 下拉菜单 < 弹窗 < 全局提示\n"

const DesignInteractionTemplateContent = "# 交互设计规范\n\n## 一、通用原则\n\n1. **一致性**：同类操作在全产品中的位置、样式、行为保持一致\n2. **及时反馈**：所有操作 100ms 内给出响应；耗时操作提供 loading 或进度反馈\n3. **容错防错**：破坏性操作必须二次确认；表单实时校验并在提交前拦截错误\n4. **可逆性**：尽量支持撤销（如删除后 toast 提供撤销入口）\n\n## 二、导航与信息架构\n\n1. 主导航层级不超过 3 级；当前位置必须有高亮或面包屑指示\n2. Tab 数量不超过 7 个，超出时改用下拉或分组\n3. 返回行为可预期：返回上一层而非首页；弹窗内操作后关闭回到触发位置\n\n## 三、表单规范\n\n1. 标签左对齐或顶对齐，必填项统一用 * 标识\n2. 提供明确的输入提示（placeholder 示例 / 格式说明），错误提示就近展示且说明如何修正\n3. 提交按钮在表单未通过校验时禁用；提交中显示 loading 防重复提交\n4. 长表单分组展示，支持分步或折叠；已填写内容离开前提醒保存\n\n## 四、反馈与提示\n\n1. 成功反馈：轻量 toast（2~3 秒自动消失），不打断流程\n2. 失败反馈：明确错误原因与解决建议；阻断性错误使用弹窗\n3. 空状态：说明原因并提供下一步操作入口（如「暂无数据，点击新建」）\n4. 加载状态：首屏用骨架屏，局部用 loading，超过 10 秒给出提示\n\n## 五、列表与数据展示\n\n1. 列表支持加载更多或分页，分页器位置与样式统一\n2. 批量操作需有选择态与已选计数\n3. 数据为空、加载失败、无权限三种状态分别设计，不可复用同一文案\n"

const DesignMobileTemplateContent = "# 移动端设计规范\n\n## 一、设计基准与适配\n\n1. 以 375×812（iPhone 标准屏）为设计基准，向下兼容 320px 小屏\n2. 采用流式布局 + 断点适配；核心内容在安全区内展示，避让刘海与底部指示条\n3. 图片按 @2x/@3x 输出，图标使用矢量格式\n\n## 二、字号与触控\n\n1. 正文不小于 14px，辅助文字不小于 12px；重要操作文字不小于 16px\n2. 可点击元素触控热区不小于 44×44px，元素间距不小于 8px，防止误触\n3. 主要操作按钮放置在拇指可达区域（屏幕下半部分）\n\n## 三、导航模式\n\n1. 一级导航 3~5 个时使用底部 Tab；超过时使用抽屉或「我的」聚合\n2. 页面层级深时顶部导航栏提供返回；手势返回（边缘滑动）需支持\n3. 禁止在移动端使用 hover 态表达关键信息（无悬停能力）\n\n## 四、内容与输入\n\n1. 单行文本截断显示省略号，重要内容支持展开\n2. 输入唤起合适的键盘类型（数字/邮箱/密码）；表单尽量自动填充\n3. 减少输入：优先使用选择器、开关、默认值替代手动输入\n\n## 五、性能与弱网\n\n1. 首屏加载控制在 3 秒内；图片压缩并使用合适尺寸\n2. 弱网/断网状态给出明确提示，已加载内容保持可读\n3. 长列表分页加载，滚动到底自动加载下一页并提供加载态\n"

const DesignChecklistTemplateContent = "# 设计走查清单\n\n> 开发提测后、上线前，设计师对照本清单逐项走查，确保还原度与体验一致。\n\n## 一、视觉还原\n\n- [ ] 色彩：主色/功能色/中性色与设计稿一致，无色值硬编码偏差\n- [ ] 字体：字号、字重、行高、颜色层级与设计稿一致\n- [ ] 间距：边距与元素间距符合 8px 栅格，对齐关系正确\n- [ ] 圆角与阴影：按规范分档，无随意自定义\n- [ ] 图标：尺寸、风格、表意与规范一致，无变形模糊\n\n## 二、布局与适配\n\n- [ ] 主流分辨率下布局正常，无内容溢出、重叠、截断异常\n- [ ] 响应式断点表现符合设计预期\n- [ ] 文本溢出处理正确（省略号/换行/ Tooltip 补全）\n- [ ] 空数据、加载中、加载失败、无权限四种状态均有设计且正确展示\n\n## 三、交互体验\n\n- [ ] 所有可点击元素有 hover/active/disabled 状态\n- [ ] 耗时操作有 loading，提交按钮防重复点击\n- [ ] 破坏性操作有二次确认；成功/失败反馈符合规范\n- [ ] 表单校验提示位置与文案正确；键盘操作与焦点态可用\n- [ ] 动效时长与缓动符合规范（无突兀跳变）\n\n## 四、一致性与可访问性\n\n- [ ] 同类组件（按钮/弹窗/分页器等）全站样式与行为一致\n- [ ] 文案语气统一，术语全产品一致（无同物多名）\n- [ ] 色彩对比度满足 WCAG AA；图片有 alt；交互元素可键盘访问\n- [ ] 深色模式（如支持）下所有页面表现正常\n\n## 五、走查结论\n\n| 问题描述 | 位置/页面 | 级别（🔴/🟡/💬） | 负责人 | 状态 |\n| --- | --- | --- | --- | --- |\n|  |  |  |  |  |\n\n> 🔴 必须修复（阻断上线）/ 🟡 建议修复（可排期）/ 💬 体验优化建议\n"

const DevelopmentGeneralTemplateContent = "# 通用研发规范\n\n## 一、命名规范\n\n1. **文件与目录**：统一使用小写中划线（kebab-case），如 `user-service.ts`、`order-handler/`\n2. **变量与函数**：使用小驼峰（camelCase），名称需表意，禁止 `a/b/c/temp/data1` 等无意义命名\n3. **常量**：使用全大写下划线（UPPER_SNAKE_CASE），如 `MAX_RETRY_COUNT`、`DEFAULT_PAGE_SIZE`\n4. **类与组件**：使用大驼峰（PascalCase），如 `UserService`、`OrderCard`\n5. **布尔值**：使用 `is/has/can/should` 前缀，如 `isEnabled`、`hasPermission`\n\n## 二、代码风格\n\n1. 禁止魔法值：所有字面量（数字、字符串、阈值）必须提取为常量\n2. 函数职责单一，建议不超过 50 行；嵌套层级不超过 3 层，超出时使用提前返回（guard clause）或提取小函数\n3. 同一逻辑出现两处及以上必须封装为可复用函数\n4. 公共 API 与复杂业务逻辑必须编写注释，说明用途、参数与边界情况\n5. 禁止提交注释掉的死代码、调试日志（`console.log` / `print`）与 TODO（确需保留的 TODO 必须注明责任人与期限）\n\n## 三、异常与日志\n\n1. 不允许空 catch / 吞异常；异常必须记录日志或向上抛出\n2. 错误信息需包含上下文（操作、关键参数），便于排查\n3. 日志分级使用：ERROR（需告警）、WARN（可容忍异常）、INFO（关键流程节点）、DEBUG（开发调试）\n4. 日志中禁止打印密码、令牌、身份证号等敏感信息\n\n## 四、安全规范\n\n1. 所有外部输入必须校验与转义，防止 SQL 注入 / XSS / 命令注入\n2. 密码、密钥等敏感配置禁止硬编码，统一走配置中心或环境变量\n3. 接口必须鉴权；越权访问（水平/垂直）需在服务端校验\n4. 敏感数据落库需加密或脱敏\n\n## 五、测试要求\n\n1. 核心业务逻辑必须编写单元测试，新代码覆盖率不低于 70%\n2. 缺陷修复必须附带回归测试用例\n3. 合并前必须通过全部 CI 检查（编译、lint、测试）\n"

const DevelopmentFrontendTemplateContent = "# 前端研发规范\n\n## 一、技术栈约定\n\n1. 框架与语言版本统一（如 React 18 + TypeScript strict 模式）\n2. 新增依赖需经团队评审，禁止引入功能重复或停止维护的库\n3. 样式方案统一（如 Tailwind CSS），禁止行内硬编码颜色/间距，使用设计 Token\n\n## 二、组件规范\n\n1. 组件职责单一，展示组件与逻辑容器分离；通用组件沉淀到共享组件库\n2. Props 必须声明类型；禁止 any，确需使用时加注释说明原因\n3. 组件文件结构：类型定义 → 常量 → 子组件 → 主组件 → 样式\n4. 列表渲染必须使用稳定 key（业务 ID），禁止使用数组下标作为 key\n\n## 三、状态与副作用\n\n1. 状态提升遵循「就近原则」，避免不必要的全局状态\n2. 副作用（请求/订阅/定时器）必须在卸载时清理\n3. 请求统一走封装的 API 层，禁止在组件内直接拼接 fetch/axios 调用\n4. 加载中、空数据、错误三种 UI 状态必须显式处理\n\n## 四、性能规范\n\n1. 路由级代码分割（懒加载），首屏资源按需加载\n2. 图片使用合适尺寸与格式，大图懒加载\n3. 高频事件（scroll/resize/input）必须防抖或节流\n4. 长列表使用虚拟滚动；避免在渲染中执行昂贵计算（使用 memo）\n\n## 五、兼容与可访问性\n\n1. 支持主流浏览器最新两个版本；使用新 API 前确认兼容性并做降级\n2. 交互元素必须支持键盘操作与焦点态；图片必须有 alt 文本\n3. 色彩对比度满足 WCAG AA（正文 ≥ 4.5:1）\n"

const DevelopmentBackendTemplateContent = "# 后端研发规范\n\n## 一、接口设计\n\n1. 遵循 RESTful 风格：资源用名词复数，动作用 HTTP 方法表达（GET/POST/PUT/PATCH/DELETE）\n2. 接口路径统一版本前缀（如 `/api/v1/`），响应结构统一（业务数据 + 错误码 + 错误信息）\n3. 分页接口统一参数（page/pageSize）与返回结构（list/total/page/pageSize）\n4. 接口变更保持向后兼容；不兼容变更必须升级版本号并通知调用方\n\n## 二、分层与依赖\n\n1. 严格分层：接口层（handler）→ 服务层（service）→ 数据层（repository），禁止跨层调用\n2. 业务逻辑写在服务层，handler 只做参数解析与响应组装\n3. 依赖单向，禁止循环依赖；共享模型下沉到公共包\n\n## 三、数据库规范\n\n1. 表与字段使用小写下划线命名；必须有主键、created_at、updated_at\n2. 字符串明确长度，金额用定点数（禁止浮点），时间统一 TIMESTAMPTZ（UTC）\n3. 高频查询字段必须建索引；禁止 SELECT *，只查询需要的字段\n4. 多表写操作必须使用事务；分页深翻页（>1万）使用游标而非 OFFSET\n5. 禁止在代码中拼接 SQL，统一使用参数化查询\n\n## 四、并发与健壮性\n\n1. 共享状态访问必须加锁或使用原子操作；注意 goroutine/线程泄漏\n2. 外部调用必须设置超时与重试（指数退避），重试接口需幂等\n3. 关键链路必须有限流、降级与熔断策略\n4. 后台任务必须可重入，失败有告警\n\n## 五、配置与环境\n\n1. 环境差异（地址、密钥、开关）全部走配置，禁止按环境写 if-else\n2. 配置变更需可热更新或有明确的发版流程\n3. 日志、监控、告警覆盖核心链路；上线必须有回滚方案\n"

const DevelopmentGitTemplateContent = "# Git 提交与分支规范\n\n## 一、分支管理\n\n1. **主干分支**：`main`（生产）/ `develop`（开发集成分支，如适用），禁止直接推送\n2. **功能分支**：`feature/<简述>`，如 `feature/prompt-market`\n3. **缺陷分支**：`fix/<简述>` 或 `hotfix/<简述>`（线上紧急修复）\n4. **发布分支**：`release/<版本号>`\n5. 分支命名使用小写中划线，禁止中文与空格；分支从最新主干切出，完成后及时删除\n\n## 二、提交信息规范（Conventional Commits）\n\n格式：`<type>(<scope>): <subject>`\n\n| type | 用途 |\n| --- | --- |\n| feat | 新功能 |\n| fix | 缺陷修复 |\n| docs | 文档变更 |\n| style | 代码格式（不影响逻辑） |\n| refactor | 重构（非 feat/fix） |\n| perf | 性能优化 |\n| test | 测试相关 |\n| chore | 构建/工具/依赖等杂项 |\n\n1. subject 不超过 50 字符，动词开头，结尾不加句号\n2. 一次提交只做一件事；大改动拆分为多个逻辑完整的提交\n3. 提交前自查：通过编译与 lint、无调试代码、无多余空白字符\n\n## 三、合并（MR/PR）规范\n\n1. 所有代码必须经 MR/PR 合入，标题清晰说明目的，描述包含：变更内容、影响范围、自测情况、关联需求/缺陷单号\n2. 单个 MR 改动建议不超过 400 行，超大 MR 需拆分\n3. 至少 1 名评审人通过后方可合并；评审意见全部解决后才能合入\n4. 合并方式统一（如 squash merge），保持主干历史整洁\n5. 合并前 CI 必须全绿；冲突由提交人负责解决\n"

const DevelopmentReviewTemplateContent = "# 代码评审（Code Review）规范\n\n## 一、评审目标\n\n1. 保证代码正确性、可维护性与团队风格一致\n2. 传播业务与系统知识，避免单点熟悉\n3. 及早发现设计缺陷，降低修复成本\n\n## 二、提交人职责\n\n1. 提交前完成自测与自查（编译、lint、单测、静态检查全通过）\n2. MR 描述清晰：业务背景、主要变更、自测结果、影响面与回滚方案\n3. 控制评审范围：单个 MR 聚焦一个目的，评审时长控制在 20 分钟以内\n4. 及时响应评审意见（建议 1 个工作日内），不阻塞他人工作\n\n## 三、评审人职责\n\n1. 优先评审，不积压；无法及时评审时主动转交\n2. 评审重点：\n   - **正确性**：逻辑错误、边界条件、空指针/越界、并发问题\n   - **完整性**：功能点遗漏、异常路径、日志与监控\n   - **一致性**：是否符合设计文档与团队规范、命名是否清晰\n   - **安全性**：注入、越权、敏感信息泄露\n   - **可维护性**：重复代码、魔法值、过度复杂、注释是否到位\n3. 意见分级：🔴 必须修改（阻断合并）/ 🟡 建议修改 / 💬 探讨，明确标注\n4. 对事不对人，描述问题与理由，给出改进建议\n\n## 四、评审流程\n\n1. 提交 MR → 自动触发 CI 与评审提醒\n2. 评审人提出意见 → 提交人修改并回复 → 评审人确认关闭\n3. 全部 🔴 意见解决且 CI 通过后，由评审人合并\n4. 紧急修复可先行合并，但必须在 24 小时内补充评审\n"

// defaultTemplates 返回平台内置默认模板列表。
func defaultTemplates() []object.PlatformTemplate {
	return []object.PlatformTemplate{
		{Category: object.TemplateCategoryProduct, Key: "demand", Label: "📝 产品需求文档", Content: ProductDemandTemplateContent},
		{Category: object.TemplateCategoryProduct, Key: "meeting", Label: "📅 会议纪要", Content: ProductMeetingTemplateContent},
		{Category: object.TemplateCategoryProduct, Key: "weekly", Label: "📊 工作周报", Content: ProductWeeklyTemplateContent},
		{Category: object.TemplateCategoryProduct, Key: "bug", Label: "🐛 Bug反馈单", Content: ProductBugTemplateContent},
		{Category: object.TemplateCategoryDesign, Key: "ui", Label: "🎨 UI 视觉设计规范", Content: DesignUiTemplateContent},
		{Category: object.TemplateCategoryDesign, Key: "interaction", Label: "🖱️ 交互设计规范", Content: DesignInteractionTemplateContent},
		{Category: object.TemplateCategoryDesign, Key: "mobile", Label: "📱 移动端设计规范", Content: DesignMobileTemplateContent},
		{Category: object.TemplateCategoryDesign, Key: "checklist", Label: "✅ 设计走查清单", Content: DesignChecklistTemplateContent},
		{Category: object.TemplateCategoryDevelopment, Key: "general", Label: "🔧 通用研发规范", Content: DevelopmentGeneralTemplateContent},
		{Category: object.TemplateCategoryDevelopment, Key: "frontend", Label: "🎨 前端研发规范", Content: DevelopmentFrontendTemplateContent},
		{Category: object.TemplateCategoryDevelopment, Key: "backend", Label: "⚙️ 后端研发规范", Content: DevelopmentBackendTemplateContent},
		{Category: object.TemplateCategoryDevelopment, Key: "git", Label: "🌿 Git 提交与分支规范", Content: DevelopmentGitTemplateContent},
		{Category: object.TemplateCategoryDevelopment, Key: "review", Label: "🔍 代码评审规范", Content: DevelopmentReviewTemplateContent},
	}
}
